name: Deploy Web

# Required CI Variables (GitHub Settings > Environments > {dev/prod} > Environment variables):
# - AWS_REGION: AWS region for deployment (e.g., us-east-1)
# - CI_ROLE: AWS IAM role ARN for OIDC authentication
# - S3_BUCKET: S3 bucket name for hosting the web app
# - CF_DISTRIBUTION: CloudFront distribution ID for cache invalidation
# - DOT_ENV: content of .env file for buidding the web app

env:
  BUILD_OUTPUT_PATH: apps/web/dist/

on:
  # push:
  pull_request:
    branches: [main]
    paths:
      - 'apps/web/**'

permissions:
  id-token: write # Allows OIDC token requests
  contents: read # Allows reading repo contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node environment
        uses: ./.github/actions/setup-node-env

      - name: Build application
        run: |
          echo "${{ vars.DOT_ENV }}" > apps/web/.env
          pnpm -F web build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_OUTPUT_PATH }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ${{ env.BUILD_OUTPUT_PATH }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.CI_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync build to S3
        run: |
          aws s3 sync ${{ env.BUILD_OUTPUT_PATH }} s3://${{ vars.S3_BUCKET }}/web \
            --delete \
            --region ${{ vars.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CF_DISTRIBUTION }} \
            --paths "/index.html" \
            --region ${{ vars.AWS_REGION }}
